name: datahack:it!
title: Datahack:it - Programming Tutorials &amp; Code Snippets
pygments: true
permalink: :title.html
paginate: 3
domain: http://www.datahack.it
paginate_path: ":num"


disqus_shortname: jbspeakr
